name: Hub Dog
author: Hub Dog
baseurl: /hubdog.github.io
description: theme for HubDog
github: http://www.github.com/HubDog
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: 283828818@qq.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
